version: '3'

vars:
  PROTO_DIR: ../proto
  GEN_DIR: ./internal/gen
  
tasks:
  # Генерация protobuf кода
  proto:
    desc: "Generate Go code from proto files"
    cmds:
      - mkdir -p {{.GEN_DIR}}
      - echo "Generating Go code from {{.PROTO_DIR}}..."
      - |
        protoc \
          -I={{.PROTO_DIR}} \
          --go_out={{.GEN_DIR}} \
          --go-grpc_out={{.GEN_DIR}} \
          --go_opt=paths=source_relative \
          --go-grpc_opt=paths=source_relative \
          {{.PROTO_DIR}}/job_service.proto
      - echo "✓ Generated in {{.GEN_DIR}}/"
  
  # Очистка сгенерированного кода
  proto-clean:
    desc: "Clean generated proto files"
    cmds:
      - rm -rf {{.GEN_DIR}}
      - echo "✓ Cleaned generated files"
  
  # Проверка валидности proto файлов
  proto-lint:
    desc: "Lint proto files"
    cmds:
      - echo "Validating proto syntax..."
      - test -f {{.PROTO_DIR}}/job_service.proto && echo "✓ Proto file exists" || echo "✗ Proto file not found"
      - echo "✓ Proto validation skipped (use 'task proto' to generate and validate)"

  # Установка protoc плагинов
  proto-deps:
    desc: "Install protoc dependencies"
    cmds:
      - echo "Installing protoc plugins..."
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - echo "✓ Plugins installed in $(go env GOPATH)/bin"
  
  # Запуск всех proto задач
  proto-all:
    desc: "Run all proto tasks (lint, generate)"
    cmds:
      - task: proto-lint
      - task: proto
  
  # Основные команды для разработки
  dev:
    desc: "Start development mode"
    cmds:
      - task: proto
      - echo "Starting dev server..."
      - go run ./cmd/worker/main.go
  
  build:
    desc: "Build the project"
    cmds:
      - task: proto
      - echo "Building..."
      - go build -o ./bin/worker ./cmd/worker
  
  test:
    desc: "Run tests"
    cmds:
      - go test ./... -v
  
  # Полная очистка проекта
  clean:
    desc: "Clean everything"
    cmds:
      - task: proto-clean
      - rm -rf ./bin
      - go clean
      - echo "✓ Project cleaned"

# Линтер
  go-lint:
    desc: "Run golangci-lint with auto-fix"
    cmds:
      - golangci-lint run --fix
    silent: false
  
  rerun:
    desc: "Пересборка контейнера и его запуск"
    cmds:
      - docker rm -f go-work-cont || echo "Контейнера не было, пропускаем"
      - docker build -t go-worker .
      - docker run -d --name go-work-cont go-worker

  run:
    desc: "Чистый запуск контейнера"
    cmds:
      - docker rm -f go-work-cont || true
      - docker run -d --rm --name go-work-cont go-worker

  rm:
    desc: "Удаление контейнера"
    cmds:
      - docker rm -f go-work-cont || true
  
  start:
    desc: "Запуск контейнера"
    cmds:
      - docker start go-work-cont

  stop:
    desc: "Остановка/пауза контейнера"
    cmds:
      - docker stop go-work-cont
